version: '3'

services: 

  web:
    build: .
    ports: 
      - "80:80"
    depends_on:
    - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
    volumes:  
      - ./data:/var/lib/mysql